Blog_App/urls.py
from django.urls import path
from . import views

app_name = "Blog_App"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
]

blog_posts/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog_app/', include('Blog_App.urls')),
    path('admin/', admin.site.urls),
]

Blog_App/models.py
from django.db import models

class Post(models.Model):
    post_text = models.CharField(max_length=200)
    posted_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post_text
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.TextField()
    commented_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_text

Blog_App/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post

def index(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, "Blog_App/index.html", context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, "Blog_App/detail.html", context)

Blog_App/templates/Blog_App/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog App</title>
</head>
<body>
    <header>
        <a href="{% url 'Blog_App:index' %}">Home</a>
    </header>
    <main>
        {% block content %}{% endblock content %}
    </main>
    <footer>
        &copy; Blog App, Brian Designs 2024
    </footer>
</body>
</html>

Blog_App/templates/Blog_App/detail.html
{% extends 'Blog_App/base.html' %}



{% block content %}
  <h1>{{post}}:</h1>

  {% for comment in post.comment_set.all %}
    <p>- {{comment}}</p>
  {% empty %}
    <p>There are no comments yet for this post.</p>
  {% endfor %}
{% endblock content %}

Blog_App/templates/Blog_App/index.html
{% extends "Blog_App/base.html" %}

{% block content %}
  {% if posts %}
    <ul>
      {% for post in posts %}
        <li><a href="{% url 'Blog_App:detail' post.id %}">{{post}}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <li>There are no posts yet</li>
  {% endif %}
{% endblock content %}